name: my_website
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.21.0
  jaspr_router: ^0.7.3
  jaspr_lucide:
   git: https://github.com/Shreemanarjun/jaspr_lucide.git
  jaspr_riverpod: ^0.3.23
  js_interop_utils: ^1.0.8
  universal_web: ^1.1.1

dev_dependencies:
  build_runner: ^2.6.0
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.21.6
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: client

